
#include "stm32f3xx_hal.h"

#ifndef BOARD_H
#define BOARD_H

#define DEBUG 1

#define LED1_PORT  GPIOC
//#define LED2_PORT  GPIOA

#define LED1_PIN   GPIO_PIN_14
//#define LED2_PIN   GPIO_PIN_15

#define LED1_ON    HAL_GPIO_WritePin(LED1_PORT, LED1_PIN, GPIO_PIN_SET) 
#define LED1_OFF   HAL_GPIO_WritePin(LED1_PORT, LED1_PIN, GPIO_PIN_RESET)
#define LED1_TOG   HAL_GPIO_TogglePin(LED1_PORT, LED1_PIN);

//#define LED2_ON    HAL_GPIO_WritePin(LED2_PORT, LED2_PIN, GPIO_PIN_RESET) 
//#define LED2_OFF   HAL_GPIO_WritePin(LED2_PORT, LED2_PIN, GPIO_PIN_SET)
//#define LED2_TOG   HAL_GPIO_TogglePin(LED2_PORT, LED2_PIN);

//#define LED_DBG_ON   LED1_ON
//#define LED_DBG_OFF  LED1_OFF
//#define LED_DBG_TOG  LED1_TOG
//
//#define LED_RUN_ON   LED2_ON
//#define LED_RUN_OFF  LED2_OFF
//#define LED_RUN_TOG  LED2_TOG

//#define BREAK_PORT  GPIOB
//#define BREAK_PIN   GPIO_PIN_11

//#define BREAK_OFF    HAL_GPIO_WritePin(BREAK_PORT, BREAK_PIN, GPIO_PIN_SET) 
//#define BREAK_ON     HAL_GPIO_WritePin(BREAK_PORT, BREAK_PIN, GPIO_PIN_RESET) 

//#define HALF_DRIVER_SD_PORT  GPIOA
//#define HALF_DRIVER_SD_PIN   GPIO_PIN_6

//#define HALF_DRIVER_SD_PORT  GPIOB
//#define HALF_DRIVER_SD_PIN   GPIO_PIN_14

#define HALF_DRIVER_SD_PORT1  GPIOA
#define HALF_DRIVER_SD_PIN1   GPIO_PIN_11
#define HALF_DRIVER_SD_PORT2  GPIOB
#define HALF_DRIVER_SD_PIN2   GPIO_PIN_1
#define HALF_DRIVER_SD_PORT3  GPIOB
#define HALF_DRIVER_SD_PIN3   GPIO_PIN_2
#define HALF_DRIVER_SD_PORT4  GPIOB
#define HALF_DRIVER_SD_PIN4   GPIO_PIN_10
#define HALF_DRIVER_SD_PORT5  GPIOB
#define HALF_DRIVER_SD_PIN5   GPIO_PIN_11

#define EN_HALF_DRIVER    {HAL_GPIO_WritePin(HALF_DRIVER_SD_PORT1, HALF_DRIVER_SD_PIN1, GPIO_PIN_SET);HAL_GPIO_WritePin(HALF_DRIVER_SD_PORT2, HALF_DRIVER_SD_PIN2, GPIO_PIN_SET);HAL_GPIO_WritePin(HALF_DRIVER_SD_PORT3, HALF_DRIVER_SD_PIN3, GPIO_PIN_SET);HAL_GPIO_WritePin(HALF_DRIVER_SD_PORT4, HALF_DRIVER_SD_PIN4, GPIO_PIN_SET);HAL_GPIO_WritePin(HALF_DRIVER_SD_PORT5, HALF_DRIVER_SD_PIN5, GPIO_PIN_SET);}

#define DIS_HALF_DRIVER   {HAL_GPIO_WritePin(HALF_DRIVER_SD_PORT1, HALF_DRIVER_SD_PIN1, GPIO_PIN_RESET);HAL_GPIO_WritePin(HALF_DRIVER_SD_PORT2, HALF_DRIVER_SD_PIN2, GPIO_PIN_RESET);HAL_GPIO_WritePin(HALF_DRIVER_SD_PORT3, HALF_DRIVER_SD_PIN3, GPIO_PIN_RESET);HAL_GPIO_WritePin(HALF_DRIVER_SD_PORT4, HALF_DRIVER_SD_PIN4, GPIO_PIN_RESET);HAL_GPIO_WritePin(HALF_DRIVER_SD_PORT5, HALF_DRIVER_SD_PIN5, GPIO_PIN_RESET);}

#define ADC1_PORT   GPIOA
#define ADC2_PORT   GPIOA

#define ADC1_PIN   GPIO_PIN_0
#define ADC2_PIN   GPIO_PIN_4

#define PWM_P_PORT   GPIOA
//#define PWM_N_PORT   GPIOB

#define PWM1P_PIN    GPIO_PIN_8
#define PWM2P_PIN    GPIO_PIN_9
#define PWM3P_PIN    GPIO_PIN_10

//#define PWM1N_PIN    GPIO_PIN_13
//#define PWM2N_PIN    GPIO_PIN_14
//#define PWM3N_PIN    GPIO_PIN_15

//#define PWM_BREAK_PORT GPIOB
//#define PWM_BREAK_PIN  GPIO_PIN_12

/* PWM INPUT */
//#define PWM_IN_PORT   GPIOC

//#define PWM_IN1_PIN    GPIO_PIN_5
//#define PWM_IN2_PIN    GPIO_PIN_6

/* QEI pins */
#define QEI_CHA_PORT GPIOA
#define QEI_CHB_PORT GPIOB
#define QEI_CHI_PORT GPIOB

#define QEI_CHA_PIN  GPIO_PIN_15
#define QEI_CHB_PIN  GPIO_PIN_3
#define QEI_CHI_PIN  GPIO_PIN_6

/* SPI pins */
#define SPI2_CLK_PORT  GPIOB
#define SPI2_MISO_PORT GPIOB
#define SPI2_MOSI_PORT GPIOB
#define SPI2_CSS_PORT  GPIOB

#define SPI2_CLK_PIN   GPIO_PIN_13
#define SPI2_MISO_PIN  GPIO_PIN_14
#define SPI2_MOSI_PIN  GPIO_PIN_15
#define SPI2_CSS_PIN   GPIO_PIN_12

#define SPI2_CSS_DIS  HAL_GPIO_WritePin(SPI2_CSS_PORT, SPI2_CSS_PIN, GPIO_PIN_SET)
#define SPI2_CSS_EN   HAL_GPIO_WritePin(SPI2_CSS_PORT, SPI2_CSS_PIN, GPIO_PIN_RESET)


void board_init(void);

#endif
